### ISSUE TITLE
add a map showing where futel phones are located

### ISSUE THREAD

**Issue by georgemandis** [kra/futel.net#10]
We could leverage GitHub's built-in handling of geoJSON files for this:

[https://help.github.com/articles/mapping-geojson-files-on-github/](https://help.github.com/articles/mapping-geojson-files-on-github/)

You could use [http://geojson.io/](http://geojson.io/) to create the JSON file. Add it to the repo and embed the map on a page per the link at the top.

Would probably also be nice to have a general list of where the phones are located, maybe even the number to reach them at?

**Comment by kra** [comment]
Nice idea, but I don't want to do this because several phones are in the front yards of their hosts. The addresses do get published, but I don't want to remove that friction myself. Might be silly but I think it's a signal for possible future hosters that they can set limits for this kind of thing. What I do want is to get around to making something for #4 with more general locations, like "SE Clinton St.".
