### ISSUE TITLE
README for jekyll branch

### ISSUE THREAD

**Issue by kra** [kra/futel.net#6]
For georgemandis:gh-pages, the rest of us aren't web devs and need to be able to test changes without ramping up too far, and basically be able to continue with this if you get hit by a bus. Also, I had to make a few local tweaks to build it, and I'm not sure if that means that changes are needed or if my local environment just doesn't match what's expected, if I had a README I would be able to make or ask for changes.

Needs a README describing
- how to build and run the site
- what the base requirements are. Ideally this will be based on a modern ubuntu or debian box. If not, then package requirements that could let us run this in a VM will work.

Also, since we're ignorant, we could use some web dev help to make this usable, even though this isn't your fault:
- is there a way to view this on github without affecting the main site? Like a dev branch or something? Maybe that's not possible?
- is there a way to make a local static copy of the rendered site?
- is there an easy way to test this for mobile browsers? I've used a Firefox plugin in the past, but IIRC Chrome has a builtin helper?

**Comment by georgemandis** [comment]
I've added a README which was automatically added to my pull request here:

[https://github.com/kra/futel.net/pull/5](https://github.com/kra/futel.net/pull/5)

Here's a preview of how the README renders on GitHub:

[https://github.com/georgemandis/futel.net/blob/09dcd03aa57adee3db71052701cc8061b1eb3927/README.md](https://github.com/georgemandis/futel.net/blob/09dcd03aa57adee3db71052701cc8061b1eb3927/README.md)

There's a lot of documentation on how to install Jekyll and the various requirements on [Jekyll's official site](http://jekyllrb.com). Rather than recreate it I mostly linked to the relevant pages there as they have step-by-step installation guides and pages for troubleshooting. 

I also linked to the official page on using Jekyll on GitHub pages, which is a pretty common/popular way of managing documentation sites: [https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)

To answer some of your questions:
- There's no way to really preview/stage the site on GitHub first prior to merging a pull request, but you can checkout the pull requests and preview the changes locally first, running Jekyll.
- A static copy of the site ends up in the `_site` folder after you run Jekyll. Basically, the files you see here are what GitHub creates and serves every time a commit is made to the repo.
- There are good mobile testing tools in Chrome, in particular a feature called "device mode." Here's some documentation on that: [https://developers.google.com/web/tools/chrome-devtools/device-mode/](https://developers.google.com/web/tools/chrome-devtools/device-mode/)

Let me know your thoughts and if you think the README is sufficient?

**Comment by kra** [comment]
Working for me, but the _site subdirectory isn't fully rendering, when I visit index.html the links and images don't work, is there a way to generate a static site, or something I have to do to see it?

**Comment by georgemandis** [comment]
If you try to access it by opening the directory in your browser that's
gonna happen. If you run jekyll serve from the terminal in the project
directory you should be able to access a local preview version of the site
at localhost:4000. Does that make-sense/help?

**Comment by kra** [comment]
Bogus, I was really hoping to be able to render a truly static site, kind of stupid that we can't do that, oh well, thanks.

**Comment by georgemandis** [comment]
It is a static site, but the problem is that when you open up index.html in
the _site folder all the paths to the CSS, images, etc are relative to
assuming it's in the root folder on a server somewhere:

/css/main.css
/images/futel_logo_black.png

etc.

If futel.net was just running on Apache or NGINX somewhere you could upload
all the _site/ files there and it would work just fine.

The Jekyll approach just makes a little more sense for some changes. If you
want to add a new page we can add it in two places instead of updating the
menu across 5 different pages. Similar situation with adding information
(like the timestamp) to the footer.

Does that make sense?

G
